# Generated by Django 5.2.16 on 2026-07-11 01:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('tipo_identificacion', models.CharField(choices=[('CEDULA', 'Cedula'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte')], max_length=20)),
                ('identificacion', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='La identificacion solo puede contener letras, numeros y guiones.', regex='^[A-Za-z0-9-]+$')])),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('SUSPENDIDA', 'Suspendida')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['identificacion'], name='usuarios_pe_identif_6939b8_idx'), models.Index(fields=['estado'], name='usuarios_pe_estado_85e8e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('PROPIETARIO', 'Propietario'), ('CONDUCTOR', 'Conductor')], max_length=30, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['codigo'], name='usuarios_ro_codigo_e11f88_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('SUSPENDIDA', 'Suspendida')], default='ACTIVA', max_length=20)),
                ('password_hash', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='usuarios.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas', to='usuarios.rol')),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='usuarios_cu_usernam_4edec8_idx'), models.Index(fields=['correo'], name='usuarios_cu_correo_2b4355_idx'), models.Index(fields=['rol', 'estado'], name='usuarios_cu_rol_id_2c6229_idx')],
            },
        ),
    ]
