# Generated by Django 5.2.16 on 2026-07-11 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_principal', models.CharField(max_length=120)),
                ('calle_secundaria', models.CharField(blank=True, max_length=120)),
                ('nro_lote', models.CharField(blank=True, max_length=40)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitud', 'longitud'], name='parqueadero_latitud_5b9d28_idx')],
            },
        ),
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='INACTIVO', max_length=20)),
                ('validado', models.BooleanField(default=False)),
                ('disponibilidad', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('LLENO', 'Lleno'), ('CERRADO', 'Cerrado')], default='CERRADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parqueadero', to='parqueaderos.direccion')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parqueaderos', to='usuarios.cuenta')),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='parqueadero', to='parqueaderos.ubicacion')),
            ],
            options={
                'indexes': [models.Index(fields=['nombre'], name='parqueadero_nombre_dd67ec_idx'), models.Index(fields=['estado'], name='parqueadero_estado_365f7f_idx'), models.Index(fields=['validado'], name='parqueadero_validad_595c6b_idx'), models.Index(fields=['disponibilidad'], name='parqueadero_disponi_cee3f2_idx'), models.Index(fields=['estado', 'validado', 'disponibilidad'], name='parqueadero_estado_a8917a_idx')],
            },
        ),
    ]
