# Generated by Django 5.2.16 on 2026-07-11 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueaderos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_espacio', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'Mantenimiento')], default='LIBRE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacios', to='parqueaderos.parqueadero')),
            ],
            options={
                'indexes': [models.Index(fields=['parqueadero', 'estado'], name='espacios_es_parquea_c8e5bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('parqueadero', 'numero_espacio'), name='uniq_espacio_por_parqueadero_numero')],
            },
        ),
    ]
