# Generated by Django 5.2.16 on 2026-07-11 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueaderos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sabado'), ('DOMINGO', 'Domingo')], max_length=20)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='parqueaderos.parqueadero')),
            ],
            options={
                'indexes': [models.Index(fields=['parqueadero', 'dia'], name='horarios_ho_parquea_34fb54_idx')],
                'constraints': [models.UniqueConstraint(fields=('parqueadero', 'dia'), name='uniq_horario_por_parqueadero_dia')],
            },
        ),
    ]
