# Generated by Django 5.2.16 on 2026-07-11 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueaderos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('GENERAL', 'General'), ('PREFERENCIAL', 'Tercera edad / discapacidad'), ('PESADOS', 'Vehiculos grandes / 4x4')], max_length=20)),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_tarifa', to='parqueaderos.parqueadero')),
            ],
            options={
                'indexes': [models.Index(fields=['parqueadero', 'codigo'], name='tarifas_cat_parquea_359ef2_idx')],
                'constraints': [models.UniqueConstraint(fields=('parqueadero', 'codigo'), name='uniq_tarifa_por_parqueadero_codigo')],
            },
        ),
    ]
