# Generated by Django 5.2.16 on 2026-07-11 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_valido', models.BooleanField(default=False)),
                ('fecha_expiracion', models.DateField(blank=True, null=True)),
                ('ruta', models.CharField(max_length=500)),
                ('file_id', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='usuarios.cuenta')),
            ],
            options={
                'indexes': [models.Index(fields=['cuenta', 'es_valido'], name='documentos__cuenta__c69f44_idx'), models.Index(fields=['fecha_expiracion'], name='documentos__fecha_e_3a54a7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_valido', True)), fields=('cuenta',), name='uniq_documento_valido_por_cuenta')],
            },
        ),
    ]
