# Generated by Django 5.2.16 on 2026-07-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        ('usuarios', '0002_cuenta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='content_type',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
        migrations.AddField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADO', 'Validado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='documento',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='documento',
            name='nombre_original',
            field=models.CharField(default='documento.pdf', max_length=255),
        ),
        migrations.AddField(
            model_name='documento',
            name='tamano_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='documento',
            index=models.Index(fields=['cuenta', 'estado'], name='documentos__cuenta__5af3fa_idx'),
        ),
    ]
